version: '3.8'
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3333:3333
  #   networks:
  #     - app-network
  #   depends_on:
  #     - db
  #   restart: on-failure
  db:
    image: bitnami/postgresql
    environment:
      POSTGRES_USER: squall
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: expenses-db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U squall -d expenses-db"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis-queue:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
volumes:
  db_data:
  dragonflydata:
networks:
  app-network:
    driver: bridge


